### ISSUE TITLE
Plugin seems broken on grafana-4.0.2

### ISSUE THREAD

**Issue by pmorgantech** [grafana/datasource-plugin-influxdb-08#10]
Installed Centos RPM: grafana-4.0.2-1481203731.x86_64

I had a few dashboards that were using the Influx-0.8 plugin.  They all stopped working upon upgrade.  The datasource still passes the validation test, but queries fail.

```
Message:
Cannot read property '_seriesQuery' of undefined

Stack trace:
TypeError: Cannot read property '_seriesQuery' of undefined
    at eval (http://grafana.xxx:8000/public/plugins/grafana-influxdb-08-datasource/datasource.js?bust=1483589508008:54:18)
    at l (http://grafana.xxx:8000/public/app/boot.85c49108.js:48:28969)
    at Function.Sg [as map] (http://grafana.xxx:8000/public/app/boot.85c49108.js:49:29676)
    at InfluxDatasource.query (http://grafana.xxx:8000/public/plugins/grafana-influxdb-08-datasource/datasource.js?bust=1483589508008:35:22)
    at h.f.issueQueries (http://grafana.xxx:8000/public/app/boot.85c49108.js:42:19495)
    at h.issueQueries (http://grafana.xxx:8000/public/app/boot.85c49108.js:18:27260)
    at g (http://grafana.xxx:8000/public/app/boot.85c49108.js:38:29545)
    at http://grafana.xxx:8000/public/app/boot.85c49108.js:38:29717
    at o.$eval (http://grafana.xxx:8000/public/app/boot.85c49108.js:39:5357)
    at o.$digest (http://grafana.xxx:8000/public/app/boot.85c49108.js:39:3843)
```

**Comment by pmorgantech** [comment]
Disregard - wallrat's PR fixes this issue for me.

**Comment by findneville** [comment]
Is there a link to this fix that you can share? Have same problem.

**Comment by pmorgantech** [comment]
Yes, I pulled in a couple line fix from a pull request that was outstanding
at the time.  FWIW I believe it was merged before 4.1 because I updated and
did not have to re-apply any fix.  In the meanwhile I upgraded to Influx
1.1, also, so I'm using the newer influx datasource.

**Comment by tinco** [comment]
It's this one: https://github.com/grafana/influxdb-08-datasource/pull/9/commits/d37371fc5868c81d23f0307cbb6f53aaf17a2ce2

The file is located at `/var/lib/grafana/plugins`

**Comment by xavi-** [comment]
Any chance d37371f could be merged to master?
